[build]
  base    = "esl-booking-system/frontend"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

# (Optional) If you ever add Netlify Functions later:
# [functions]
#   directory = "netlify/functions"
